import Head from "next/head";
import Image from "next/image";

// Image importing
import BrannerImage from "../public/BrannerImage.png";

export default function Bikes() {
  return (
    <>
      <Head>
        <title>Bikes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      {/* Div for margin:0 and padding:0 for all elements */}
      <div className="m-0 p-0  ">
        {/* Main tag for main content */}
        <main className="blackbox w-[90vw] mx-auto bg-white h-max rounded-md p-6">

          <div className="bikes grid grid-cols-2 justify-around items-center sm:flex sm:flex-col lg:flex lg:flex-col sm:items-center lg:items-center">

            <div className="bikeone w-[40vw] h-[35rem] shadow-sm shadow-black rounded-xl sm:w-[70vw] lg:w-[70vw] sm:h-[26rem] lg:h-[33rem] sm:mb-4 lg:mb-4">
              {/* Div for image color box */}
              <div className="imagebackbox w-[40vw] h-[20rem] rounded-t-xl bg-gradient-to-r from-[#42275a] to-[#734b6d] flex justify-around items-center sm:w-[70vw] lg:w-[70vw] sm:h-[10rem] lg:h-[18rem]">
                <Image
                  src={BrannerImage}
                  alt='Loading'
                  className='w-[30vw] h-max rounded-md sm:w-[50vw] lg:w-[50vw]'
                  priority
                />
              </div>
              <div className="heading h-[6rem] flex items-center">
                <h1 className='mx-5 text-2xl font-bold my-4'>Bike </h1>
              </div>
              <h1 className='mx-5 text-xl font-semibold my-2'>Ex-show-room Price: ₹21,0000 </h1>
              <h1 className='mx-5 text-lg my-2'>Engine: 1000cc </h1>
              <h1 className='mx-5 text-base my-2'>Top Speed: 200 Kmph </h1>
            </div>

            <div className="bikeone w-[40vw] h-[35rem] shadow-sm shadow-black rounded-xl sm:w-[70vw] lg:w-[70vw] sm:h-[26rem] lg:h-[33rem] sm:mb-4 lg:mb-4">
              {/* Div for image color box */}
              <div className="imagebackbox w-[40vw] h-[20rem] rounded-t-xl bg-gradient-to-r from-[#42275a] to-[#734b6d] flex justify-around items-center sm:w-[70vw] lg:w-[70vw] sm:h-[10rem] lg:h-[18rem]">
                <Image
                  src={BrannerImage}
                  alt='Loading'
                  className='w-[30vw] h-max rounded-md sm:w-[50vw] lg:w-[50vw]'
                  priority
                />
              </div>
              <div className="heading h-[6rem] flex items-center">
                <h1 className='mx-5 text-2xl font-bold my-4'>Bike </h1>
              </div>
              <h1 className='mx-5 text-xl font-semibold my-2'>Ex-show-room Price: ₹21,0000 </h1>
              <h1 className='mx-5 text-lg my-2'>Engine: 1000cc </h1>
              <h1 className='mx-5 text-base my-2'>Top Speed: 200 Kmph </h1>
            </div>

          </div>

        </main>
      </div>

      {/* Text changing div */}
      <div className="textbox my-8 h-[5rem] hidden">
        <h2 className="h1tag text-center font-bold text-5xl transition-all duration-700 font-[cursive]"></h2>
      </div>
    </>
  );
}
