import Head from "next/head";
import Image from "next/image";

// Image importing
import BrannerImage from "../public/BrannerImage.png";

export default function BikeBlogs() {
  return (
    <>
      <Head>
        <title>BikeBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      {/* Div for margin:0 and padding:0 for all elements */}
      <div className="m-0 p-0  ">

        {/* Main tag for main content */}
        <main className="blackbox w-[90vw] mx-auto bg-white h-max rounded-md p-6">

          {/* Div for blogs */}
          <div className="blogsdiv grid grid-cols-2 justify-around items-center sm:flex sm:flex-col sm:items-center lg:flex lg:flex-col lg:items-center">

            <div className="blogone w-[40vw] h-[30rem] border-2 shadow-md p-2 rounded-md my-2 sm:w-[77vw] lg:w-[77vw]">
              <Image
                src={BrannerImage}
                alt='Loading'
                className="w-[30vw] h-max mx-auto rounded-lg mt-4 sm:w-[70vw] lg:w-[50vw]"
                priority
              />
              <h1 className='my-3 ml-5 text-base'>UploadedOn: 20 Nov 2022 05:00pm </h1>
              <h1 className='my-3 ml-5 text-xl'>Addedby: Manjunath </h1>
              <h1 className='my-3 mx-5 text-sm'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque nam. Ipsam illo impedit nobis natus cupiditate vero, odit totam ipsa saepe iusto autem quaerat iste expedita earum laborum at!</h1>
            </div>

            <div className="blogone w-[40vw] h-[30rem] border-2 shadow-md p-2 rounded-md my-2 sm:w-[77vw] lg:w-[77vw]">
              <Image
                src={BrannerImage}
                alt='Loading'
                className="w-[30vw] h-max mx-auto rounded-lg mt-4 sm:w-[70vw] lg:w-[50vw]"
                priority
              />
              <h1 className='my-3 ml-5 text-base'>UploadedOn: 20 Nov 2022 05:00pm </h1>
              <h1 className='my-3 ml-5 text-xl'>Addedby: Manjunath </h1>
              <h1 className='my-3 mx-5 text-sm'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque nam. Ipsam illo impedit nobis natus cupiditate vero, odit totam ipsa saepe iusto autem quaerat iste expedita earum laborum at!</h1>
            </div>

          </div>
        </main>
      </div>

      {/* Text changing div */}
      <div className="textbox my-8 h-[5rem] hidden">
        <h2 className="h1tag text-center font-bold text-5xl transition-all duration-700 font-[cursive]"></h2>
      </div>
    </>
  );
}
