/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'

// Image importing
import BrannerImage from '../public/BrannerImage.png'

export default function Home() {

  // Function for changing text
  useEffect(() => {
    setInterval(function () {
      let H1Tag = document.getElementsByClassName('h1tag')[0]
      H1Tag.style.color = 'black'
      H1Tag.innerHTML = 'Motor cycle it is not a bike.'
    }, 4000);
  })

  // Function for changing text
  useEffect(function () {
    setInterval(() => {
      let H1Tag = document.getElementsByClassName('h1tag')[0]
      H1Tag.style.color = 'green'
      H1Tag.innerHTML = 'Its a emotion.'
    }, 8000);
  })

  return (
    <>
      <Head>
        <title>Gear Works</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      {/* Div for margin:0 and padding:0 for all elements */}
      <div className="m-0 p-0  ">

        {/* Main tag for main content */}
        <main className="blackbox w-[90vw] mx-auto bg-white h-max rounded-md p-6">

          {/* Branner image tag */}
          <Image src={BrannerImage} className='mx-auto w-[80vw] h-max rounded-md' />

          {/* Text changing div */}
          <div className="textbox my-8 h-[5rem]">
            <h2 className='h1tag text-center font-bold text-5xl transition-all duration-700 font-[cursive]'></h2>
          </div>

          <hr />

          <div className="scalesbox">
            <h1 className=' text-3xl font-bold text-center'>GearWorks is NO .1 company in selling bike market. See our latest sales recorde.</h1>
          </div>

        </main>

      </div>

    </>
  )
}
